name: Mac Build/Test

on:
  # allows us to run workflows manually
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/windows_build_test.yml'

  release:
    types: # This configuration does not affect the page_build event above
      - created
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  BuildTest:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initial setup
        shell: bash -l {0}
        run: |
          brew install eigen hdf5

      - name: Environment Variables
        shell: bash -l {0}
        run: |
          echo "HOME=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV


      - name: Build MOAB
        shell: bash -l {0}
        run: |
          cd ${HOME}
          mkdir -pv moab/bld
          cd moab
          git clone https://bitbucket.org/fathomteam/moab -b 5.5.1 --depth 1 --shallow-submodules
          cd bld
          cmake ../moab -DENABLE_HDF5=ON \
                        -DENABLE_PYMOAB=OFF \
                        -DHDF5_ROOT=$HDF5_PATH \
                        -DBUILD_SHARED_LIBS=ON \
                        -DENABLE_BLASLAPACK=OFF \
                        -DENABLE_FORTRAN=OFF \
                        -DCMAKE_INSTALL_PREFIX=${HOME}/moab
          make
          make install
          rm -rf ${HOME}/moab/moab ${HOME}/moab/bld
